const initialState = {
  id: 3741352,
  username: 'dani_ramrez',
  resource_state: 3,
  firstname: 'Dani',
  lastname: 'Ramírez',
  city: 'Sant Just Desvern',
  state: 'Catalonia',
  country: 'Spain',
  sex: 'M',
  premium: true,
  summit: true,
  created_at: '2014-01-19T08:51:33Z',
  updated_at: '2020-11-14T23:00:06Z',
  badge_type_id: 1,
  profile_medium:
    'https://dgalywyr863hv.cloudfront.net/pictures/athletes/3741352/2032398/4/medium.jpg',
  profile:
    'https://dgalywyr863hv.cloudfront.net/pictures/athletes/3741352/2032398/4/large.jpg',
  friend: null,
  follower: null,
  follower_count: 80,
  friend_count: 101,
  mutual_friend_count: 0,
  athlete_type: 1,
  date_preference: '%m/%d/%Y',
  measurement_preference: 'meters',
  clubs: [
    {
      id: 299845,
      resource_state: 2,
      name: 'GINGER RUNNER VIRTUAL RUN 2017',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/299845/6789987/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/299845/6789987/1/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/299845/6795719/1/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/299845/6795719/1/small.jpg',
      sport_type: 'running',
      city: 'Seattle',
      state: 'Washington',
      country: 'United States',
      private: true,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'GRVR17',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 158549,
      resource_state: 2,
      name: 'Salomon Running',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/3390750/2/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/3390750/2/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/4449838/9/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/158549/4449838/9/small.jpg',
      sport_type: 'running',
      city: 'Annecy',
      state: 'Auvergne-Rhône-Alpes',
      country: 'France',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'salomonrunning',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 47423,
      resource_state: 2,
      name: 'Train. Race. Beer.',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/47423/1183580/2/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/47423/1183580/2/large.jpg',
      cover_photo: null,
      cover_photo_small: null,
      sport_type: 'running',
      city: 'Los Angeles',
      state: 'California',
      country: 'United States',
      private: false,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'trainracebeer',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 316628,
      resource_state: 2,
      name: 'TRAILRUNNINGReview',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/316628/7387583/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/316628/7387583/1/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/316628/8714809/11/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/316628/8714809/11/small.jpg',
      sport_type: 'other',
      city: 'Barcelona',
      state: 'Barcelona',
      country: 'Spain',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'trailrunningreview',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 157958,
      resource_state: 2,
      name: 'TRAILRUNNINGReview Test Team',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/157958/3366917/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/157958/3366917/1/large.jpg',
      cover_photo: null,
      cover_photo_small: null,
      sport_type: 'running',
      city: '',
      state: '',
      country: 'España',
      private: false,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'TRAILRUNNINGReview-Team',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 123944,
      resource_state: 2,
      name: 'Els reptes del Doctor Soler',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/123944/2367166/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/123944/2367166/1/large.jpg',
      cover_photo: null,
      cover_photo_small: null,
      sport_type: 'running',
      city: '',
      state: 'Catalunya',
      country: 'Espanya',
      private: false,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'reptessoler',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 240766,
      resource_state: 2,
      name: 'Zurich Marató Barcelona',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/240766/5296207/2/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/240766/5296207/2/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/240766/5296195/13/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/240766/5296195/13/small.jpg',
      sport_type: 'running',
      city: "L'Hospitalet De Llobregat",
      state: 'Barcelona',
      country: 'Spain',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'ZurichMaratoBarcelona',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 47342,
      resource_state: 2,
      name: 'Trail Run BCN',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/47342/1182125/1/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/47342/1182125/1/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/47342/5276810/2/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/47342/5276810/2/small.jpg',
      sport_type: 'running',
      city: 'Barcelona',
      state: 'Cataluña',
      country: 'España',
      private: false,
      member_count: 0,
      featured: false,
      verified: false,
      url: 'trailrunbcn',
      membership: 'member',
      admin: false,
      owner: false,
    },
    {
      id: 706608,
      resource_state: 2,
      name: 'FGC Turisme Outdoor',
      profile_medium:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/706608/16032400/2/medium.jpg',
      profile:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/706608/16032400/2/large.jpg',
      cover_photo:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/706608/16090056/6/large.jpg',
      cover_photo_small:
        'https://dgalywyr863hv.cloudfront.net/pictures/clubs/706608/16090056/6/small.jpg',
      sport_type: 'other',
      city: 'Barcelona',
      state: 'Barcelona',
      country: 'Spain',
      private: false,
      member_count: 0,
      featured: false,
      verified: true,
      url: 'FGCTurismeOutdoor',
      membership: 'member',
      admin: false,
      owner: false,
    },
  ],
  ftp: null,
  weight: 56,
  bikes: [],
  shoes: [
    {
      id: 'g4343047',
      primary: false,
      name: 'New Balance kom',
      resource_state: 2,
      distance: 158903,
    },
    {
      id: 'g5730336',
      primary: true,
      name: 'Salomon Sense Ride 3',
      resource_state: 2,
      distance: 341210,
    },
    {
      id: 'g2530386',
      primary: false,
      name: 'Salomon S-Lab Sense Ultra',
      resource_state: 2,
      distance: 139789,
    },
    {
      id: 'g4970645',
      primary: false,
      name: 'New Balance Fresh Foam Zante Pursuit',
      resource_state: 2,
      distance: 190767,
    },
    {
      id: 'g3055064',
      primary: false,
      name: 'HOKA ONE ONE Speed Instinct 2',
      resource_state: 2,
      distance: 130621,
    },
    {
      id: 'g4380128',
      primary: false,
      name: 'Salomon Ultra pro',
      resource_state: 2,
      distance: 234262,
    },
    {
      id: 'g3821222',
      primary: false,
      name: 'Salomon Sense Ride Black ones',
      resource_state: 2,
      distance: 298358,
    },
  ],
};
export default function reducer(state = initialState, action) {
  switch (action.type) {
    case 'SET_USER':
      return action.payload;
    default:
      return state;
  }
}
